version: '3'
services:
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      app:
        ipv4_address: 172.77.0.8
  web:
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      app:
        ipv4_address: 172.77.0.3
  mysql:
    ports:
    - 3301:3306
    volumes:
      - mysql_storage:/var/lib/mysql
    networks:
      app:
        ipv4_address: 172.77.0.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker

volumes:
  mysql_storage:

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.77.0.0/16